---@diagnostic disable: undefined-global
---------------------------------------------------------
-- AUTOGENERATED HYPRLAND CONFIG.                      --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.--
---------------------------------------------------------

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

------------------
---- MONITORS ----
------------------

hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "0x0",
	scale = 1.25,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "auto-right",
	scale = 1,
})

---------------------
---- MY PROGRAMS ----
---------------------

local terminal = "kitty"
local fileManager = "dolphin"
local menu = "hyprlauncher"

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
	hl.exec_cmd(terminal)
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("waybar & hyprpaper & firefox")
end)

-------------------
---- WORKFLOWS ---- --[cite: 12]
-------------------

hl.env("WORKFLOW", "powersaver")
hl.env("WORKFLOW_ICON", "")
hl.env(
	"WORKFLOW_DESCRIPTION",
	"Saves as much power as possible by disabling all animations and effects, but preserving readability"
)
hl.env("WORKFLOWS_PATH", "./workflows/powersaver.conf")

hl.config({
	source = "./workflows/powersaver.conf",
})

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 15,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
			inactive_border = "rgba(595959aa)",
		},
		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},
		blur = {
			enabled = true,
			size = 3,
			passes = 1,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = false,
	},
})

-- Curves and animations
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

hl.config({
	dwindle = {
		preserve_split = true,
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = false,
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = -0.5,
		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local keybindings = {
	variables = {
		mainMod = "SUPER",
		TERMINAL = "kitty",
		EDITOR = "code",
		EXPLORER = "dolphin",
		BROWSER = "qutebrowser",
		KILLACTIVE = 'hyprctl dispatch killactive ""',
		music = "flatpak run com.spotify.Client",
		rofi_launch = "hyde-shell rofilaunch",
	},
	categories = {
		{
			name = "Window Management",
			subgroups = {
				{
					name = nil,
					binds = {
						{
							type = "bindd",
							mod = "$mainMod",
							key = "Q",
							desc = "close focused window",
							action = "exec, $KILLACTIVE",
						},
						{
							type = "bindd",
							mod = "Alt",
							key = "F4",
							desc = "close focused window",
							action = "exec, $KILLACTIVE",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "Delete",
							desc = "kill hyprland session",
							action = "exec, hyde-shell logout",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "W",
							desc = "Toggle floating",
							action = "togglefloating",
						},
						{ type = "bindd", mod = "$mainMod", key = "G", desc = "toggle group", action = "togglegroup" },
						{
							type = "bindd",
							mod = "Shift",
							key = "F11",
							desc = "toggle fullscreen",
							action = "fullscreen",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "L",
							desc = "lock screen",
							action = "exec, hyde-shell lock-session",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "J",
							desc = "toggle pin on focused window",
							action = "exec, hyde-shell window.pin",
						},
						{
							type = "bindd",
							mod = "Control Alt",
							key = "Delete",
							desc = "logout menu",
							action = "exec, hyde-shell logoutlaunch",
						},
						{
							type = "bindd",
							mod = "Alt_R",
							key = "Control_R",
							desc = "toggle waybar and reload config",
							action = "exec, hyde-shell waybar --hide",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "J",
							desc = "toggle split",
							action = "layoutmsg, togglesplit",
						},
					},
				},
				{
					name = "Group Navigation",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "H",
							desc = "change active group backwards",
							action = "changegroupactive, b",
						},
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "L",
							desc = "change active group forwards",
							action = "changegroupactive, f",
						},
					},
				},
				{
					name = "Change focus",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod",
							key = "Left",
							desc = "focus left",
							action = "movefocus, l",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "Right",
							desc = "focus right",
							action = "movefocus, r",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "Up",
							desc = "focus up",
							action = "movefocus, u",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "Down",
							desc = "focus down",
							action = "movefocus, d",
						},
						{ type = "bindd", mod = "ALT", key = "Tab", desc = "Cycle focus", action = "cyclenext" },
					},
				},
				{
					name = "Resize Active Window",
					binds = {
						{
							type = "bindde",
							mod = "$mainMod Shift",
							key = "Right",
							desc = "resize window right",
							action = "resizeactive, 30 0",
						},
						{
							type = "bindde",
							mod = "$mainMod Shift",
							key = "Left",
							desc = "resize window left",
							action = "resizeactive, -30 0",
						},
						{
							type = "bindde",
							mod = "$mainMod Shift",
							key = "Up",
							desc = "resize window up",
							action = "resizeactive, 0 -30",
						},
						{
							type = "bindde",
							mod = "$mainMod Shift",
							key = "Down",
							desc = "resize window down",
							action = "resizeactive, 0 30",
						},
					},
				},
				{
					name = "Move active window across workspace",
					binds = {
						{
							type = "bindde",
							mod = "$mainMod Shift Control",
							key = "left",
							desc = "Move active window to the left",
							action = 'exec, grep -q "true" <<< $(hyprctl activewindow -j | jq -r .floating) && hyprctl dispatch moveactive -30 0 || hyprctl dispatch movewindow l',
						},
						{
							type = "bindde",
							mod = "$mainMod Shift Control",
							key = "right",
							desc = "Move active window to the right",
							action = 'exec, grep -q "true" <<< $(hyprctl activewindow -j | jq -r .floating) && hyprctl dispatch moveactive 30 0 || hyprctl dispatch movewindow r',
						},
						{
							type = "bindde",
							mod = "$mainMod Shift Control",
							key = "up",
							desc = "Move active window up",
							action = 'exec, grep -q "true" <<< $(hyprctl activewindow -j | jq -r .floating) && hyprctl dispatch moveactive 0 -30 || hyprctl dispatch movewindow u',
						},
						{
							type = "bindde",
							mod = "$mainMod Shift Control",
							key = "down",
							desc = "Move active window down",
							action = 'exec, grep -q "true" <<< $(hyprctl activewindow -j | jq -r .floating) && hyprctl dispatch moveactive 0 30 || hyprctl dispatch movewindow d',
						},
					},
				},
				{
					name = "Move & Resize with mouse",
					binds = {
						{
							type = "binddm",
							mod = "$mainMod",
							key = "mouse:272",
							desc = "hold to move window",
							action = "movewindow",
						},
						{
							type = "binddm",
							mod = "$mainMod",
							key = "mouse:273",
							desc = "hold to resize window",
							action = "resizewindow",
						},
						{
							type = "binddm",
							mod = "$mainMod",
							key = "Z",
							desc = "hold to move window",
							action = "movewindow",
						},
						{
							type = "binddm",
							mod = "$mainMod",
							key = "X",
							desc = "hold to resize window",
							action = "resizewindow",
						},
					},
				},
			},
		},
		{
			name = "Launcher",
			subgroups = {
				{
					name = "Apps",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod",
							key = "T",
							desc = "terminal emulator",
							action = "exec, $TERMINAL",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "T",
							desc = "dropdown terminal",
							action = "exec, hyde-shell pypr toggle console",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "E",
							desc = "yazi-float file manager",
							action = "exec, kitty -o confirm_os_window_close=0 --class yazi-float -e yazi", --[cite: 11]
						},
						{ type = "bindd", mod = "$mainMod", key = "C", desc = "text editor", action = "exec, $EDITOR" },
						{ type = "bindd", mod = "$mainMod", key = "B", desc = "music", action = "exec, $music" },
						{
							type = "bindd",
							mod = "$mainMod",
							key = "F",
							desc = "web browser",
							action = "exec, $BROWSER",
						},
						{
							type = "bindd",
							mod = "Control Shift",
							key = "Escape",
							desc = "system monitor",
							action = "exec, hyde-shell system.monitor",
						},
					},
				},
				{
					name = "Rofi menus",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod",
							key = "A",
							desc = "application finder",
							action = "exec, pkill -x rofi || $rofi-launch d",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "TAB",
							desc = "window switcher",
							action = "exec, pkill -x rofi || $rofi-launch w",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "E",
							desc = "file finder",
							action = "exec, pkill -x rofi || hyde-shell f",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "slash",
							desc = "keybindings hint",
							action = "exec, pkill -x rofi || hyde-shell keybinds_hint c",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "comma",
							desc = "emoji picker",
							action = "exec, pkill -x rofi || hyde-shell emoji-picker",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "period",
							desc = "glyph picker",
							action = "exec, pkill -x rofi || hyde-shell glyph-picker",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "V",
							desc = "clipboard",
							action = "exec, pkill -x rofi || hyde-shell cliphist -c",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "V",
							desc = "clipboard manager",
							action = "exec, pkill -x rofi || hyde-shell cliphist",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "A",
							desc = "select rofi launcher",
							action = "exec, pkill -x rofi || hyde-shell rofiselect",
						},
					},
				},
			},
		},
		{
			name = "Hardware Controls",
			subgroups = {
				{
					name = "Audio",
					binds = {
						{
							type = "binddl",
							mod = "",
							key = "XF86AudioMute",
							desc = "toggle mute output",
							action = "exec, hyde-shell volumecontrol -o m",
						},
						{
							type = "binddl",
							mod = "",
							key = "XF86AudioMicMute",
							desc = "un/mute microphone",
							action = "exec, hyde-shell volumecontrol -i m",
						},
						{
							type = "binddel",
							mod = "",
							key = "XF86AudioLowerVolume",
							desc = "decrease volume",
							action = "exec, hyde-shell volumecontrol -o d",
						},
						{
							type = "binddel",
							mod = "",
							key = "XF86AudioRaiseVolume",
							desc = "increase volume",
							action = "exec, hyde-shell volumecontrol -o i",
						},
						{
							type = "binddl",
							mod = "",
							key = "F5",
							desc = "toggle mute output",
							action = "exec, hyde-shell volumecontrol -o m",
						},
						{
							type = "binddel",
							mod = "",
							key = "F6",
							desc = "decrease volume",
							action = "exec, hyde-shell volumecontrol -o d",
						},
						{
							type = "binddel",
							mod = "",
							key = "F7",
							desc = "increase volume",
							action = "exec, hyde-shell volumecontrol -o i",
						},
					},
				},
				{
					name = "Media",
					binds = {
						{
							type = "binddl",
							mod = "",
							key = "XF86AudioPlay",
							desc = "play media",
							action = "exec, playerctl play-pause",
						},
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "M",
							desc = "toggle mute/unmute for active-window",
							action = "exec, hyde-shell window.mute",
						},
						{
							type = "binddel",
							mod = "Ctrl Shift",
							key = "Right",
							desc = "next media",
							action = "exec, playerctl next",
						},
						{
							type = "binddel",
							mod = "Ctrl Shift",
							key = "Left",
							desc = "previous media",
							action = "exec, playerctl previous",
						},
					},
				},
				{
					name = "Brightness",
					binds = {
						{
							type = "binddel",
							mod = "",
							key = "XF86MonBrightnessUp",
							desc = "increase brightness",
							action = "exec, hyde-shell brightnesscontrol i",
						},
						{
							type = "binddel",
							mod = "",
							key = "XF86MonBrightnessDown",
							desc = "decrease brightness",
							action = "exec, hyde-shell brightnesscontrol d",
						},
						{
							type = "binddel",
							mod = "",
							key = "F3",
							desc = "decrease brightness",
							action = "exec, hyde-shell brightnesscontrol d",
						},
						{
							type = "binddel",
							mod = "",
							key = "F4",
							desc = "increase brightness",
							action = "exec, hyde-shell brightnesscontrol i",
						},
					},
				},
			},
		},
		{
			name = "Utilities",
			subgroups = {
				{
					name = nil,
					binds = {
						{
							type = "binddl",
							mod = "$mainMod",
							key = "K",
							desc = "toggle keyboard layout",
							action = "exec, hyde-shell keyboardswitch",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "G",
							desc = "game mode",
							action = "exec, hyde-shell gamemode",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "G",
							desc = "open game launcher",
							action = "exec, hyde-shell gamelauncher",
						},
					},
				},
				{
					name = "Screen Capture",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "P",
							desc = "color picker",
							action = "exec, hyprpicker -an",
						},
						{
							type = "bindd",
							mod = "$mainMod+Shift",
							key = "M",
							desc = "snip screen",
							action = "exec, hyde-shell screenshot s",
						},
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "P",
							desc = "freeze and snip screen",
							action = "exec, hyde-shell screenshot sf",
						},
						{
							type = "binddl",
							mod = "$mainMod Alt",
							key = "P",
							desc = "print monitor",
							action = "exec, hyde-shell screenshot m",
						},
						{
							type = "binddl",
							mod = "",
							key = "Print",
							desc = "print all monitors",
							action = "exec, hyde-shell screenshot p",
						},
					},
				},
			},
		},
		{
			name = "Theming and Wallpaper",
			subgroups = {
				{
					name = nil,
					binds = {
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "Right",
							desc = "next global wallpaper",
							action = "exec, hyde-shell wallpaper -Gn",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "Left",
							desc = "previous global wallpaper",
							action = "exec, hyde-shell wallpaper -Gp",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "W",
							desc = "select a global wallpaper",
							action = "exec, pkill -x rofi || hyde-shell wallpaper -SG",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "Up",
							desc = "next waybar layout",
							action = "exec, hyde-shell wbarconfgen n",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "Down",
							desc = "previous waybar layout",
							action = "exec, hyde-shell wbarconfgen p",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "R",
							desc = "wallbash mode selector",
							action = "exec, pkill -x rofi || hyde-shell wallbashtoggle -m",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "T",
							desc = "select a theme",
							action = "exec, pkill -x rofi || hyde-shell themeselect",
						},
						{
							type = "bindd",
							mod = "$mainMod+Shift",
							key = "Y",
							desc = "select animations",
							action = "exec, pkill -x rofi || hyde-shell animations --select",
						},
						{
							type = "bindd",
							mod = "$mainMod+Shift",
							key = "U",
							desc = "select hyprlock layout",
							action = "exec, pkill -x rofi || hyde-shell hyprlock --select",
						},
					},
				},
			},
		},
		{
			name = "Workspaces",
			subgroups = {
				{
					name = "Navigation",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod",
							key = "1",
							desc = "navigate to workspace 1",
							action = "workspace, 1",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "2",
							desc = "navigate to workspace 2",
							action = "workspace, 2",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "3",
							desc = "navigate to workspace 3",
							action = "workspace, 3",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "4",
							desc = "navigate to workspace 4",
							action = "workspace, 4",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "5",
							desc = "navigate to workspace 5",
							action = "workspace, 5",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "6",
							desc = "navigate to workspace 6",
							action = "workspace, 6",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "7",
							desc = "navigate to workspace 7",
							action = "workspace, 7",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "8",
							desc = "navigate to workspace 8",
							action = "workspace, 8",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "9",
							desc = "navigate to workspace 9",
							action = "workspace, 9",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "0",
							desc = "navigate to workspace 10",
							action = "workspace, 10",
						},
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "Right",
							desc = "change active workspace forwards",
							action = "workspace, r+1",
						},
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "Left",
							desc = "change active workspace backwards",
							action = "workspace, r-1",
						},
						{
							type = "bindd",
							mod = "$mainMod Control",
							key = "Down",
							desc = "navigate to the nearest empty workspace",
							action = "workspace, empty",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "mouse_down",
							desc = "next workspace",
							action = "workspace, e+1",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "mouse_up",
							desc = "previous workspace",
							action = "workspace, e-1",
						},
					},
				},
				{
					name = "Navigation | Special workspace",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "S",
							desc = "move to scratchpad",
							action = "movetoworkspace, special",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "S",
							desc = "move to scratchpad (silent)",
							action = "movetoworkspacesilent, special",
						},
						{
							type = "bindd",
							mod = "$mainMod",
							key = "S",
							desc = "toggle scratchpad",
							action = "togglespecialworkspace",
						},
					},
				},
				{
					name = "Move window to workspace",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "1",
							desc = "move to workspace 1",
							action = "movetoworkspace, 1",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "2",
							desc = "move to workspace 2",
							action = "movetoworkspace, 2",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "3",
							desc = "move to workspace 3",
							action = "movetoworkspace, 3",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "4",
							desc = "move to workspace 4",
							action = "movetoworkspace, 4",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "5",
							desc = "move to workspace 5",
							action = "movetoworkspace, 5",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "6",
							desc = "move to workspace 6",
							action = "movetoworkspace, 6",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "7",
							desc = "move to workspace 7",
							action = "movetoworkspace, 7",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "8",
							desc = "move to workspace 8",
							action = "movetoworkspace, 8",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "9",
							desc = "move to workspace 9",
							action = "movetoworkspace, 9",
						},
						{
							type = "bindd",
							mod = "$mainMod Shift",
							key = "0",
							desc = "move to workspace 10",
							action = "movetoworkspace, 10",
						},
						{
							type = "bindd",
							mod = "$mainMod Control+Alt",
							key = "Right",
							desc = "move window to next relative workspace",
							action = "movetoworkspace, r+1",
						},
						{
							type = "bindd",
							mod = "$mainMod Control+Alt",
							key = "Left",
							desc = "move window to previous relative workspace",
							action = "movetoworkspace, r-ireserve",
						},
					},
				},
				{
					name = "Navigation | Move window silently",
					binds = {
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "1",
							desc = "move to workspace 1 (silent)",
							action = "movetoworkspacesilent, 1",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "2",
							desc = "move to workspace 2 (silent)",
							action = "movetoworkspacesilent, 2",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "3",
							desc = "move to workspace 3 (silent)",
							action = "movetoworkspacesilent, 3",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "4",
							desc = "move to workspace 4 (silent)",
							action = "movetoworkspacesilent, 4",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "5",
							desc = "move to workspace 5 (silent)",
							action = "movetoworkspacesilent, 5",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "6",
							desc = "move to workspace 6 (silent)",
							action = "movetoworkspacesilent, 6",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "7",
							desc = "move to workspace 7 (silent)",
							action = "movetoworkspacesilent, 7",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "8",
							desc = "move to workspace 8 (silent)",
							action = "movetoworkspacesilent, 8",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "9",
							desc = "move to workspace 9 (silent)",
							action = "movetoworkspacesilent, 9",
						},
						{
							type = "bindd",
							mod = "$mainMod Alt",
							key = "0",
							desc = "move to workspace 10 (silent)",
							action = "movetoworkspacesilent, 10",
						},
					},
				},
			},
		},
	},
}

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },
	move = "20 monitor_h-120",
	float = true,
})

-- ==== Source 11 Added Window & Layer Rules ==== --[cite: 11]

-- Yazi Float
hl.window_rule({
	name = "yazi-float",
	match = { class = "^(yazi-float)$" },
	float = true,
	center = true,
	size = "75% 80%",
})

-- Idle Inhibit
hl.window_rule({ idle_inhibit = "fullscreen", match = { class = "^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$" } })
hl.window_rule({ idle_inhibit = "fullscreen", match = { class = "^(.*[Ss]potify.*)$" } })
hl.window_rule({
	idle_inhibit = "fullscreen",
	match = {
		class = "^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$",
	},
})

-- Picture-in-Picture
hl.window_rule({
	name = "hyde_picture_in_picture",
	match = { title = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$" },
	tag = { "+picture-in-picture", "+hyde_picture_in_picture" },
	float = true,
	keep_aspect_ratio = true,
	move = "(monitor_w*0.73) (monitor_h*0.72)",
	size = "(monitor_w*0.25) (monitor_h*0.25)",
	pin = true,
})

-- Opacity Rules
hl.window_rule({ opacity = "0.90 $& 0.90 $& 1", match = { class = "^(firefox)$" } })
hl.window_rule({ opacity = "0.90 $& 0.90 $& 1", match = { class = "^(zen)$" } })
hl.window_rule({ opacity = "0.90 $& 0.90 $& 1", match = { class = "^(brave-browser)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(code-oss)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^([Cc]ode)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(code-url-handler)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(code-insiders-url-handler)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(kitty)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(org.kde.dolphin)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(org.kde.ark)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(nwg-look)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(qt5ct)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(qt6ct)$" } })
hl.window_rule({ opacity = "0.80 $& 0.80 $& 1", match = { class = "^(kvantummanager)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(org.pulseaudio.pavucontrol)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(blueman-manager)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(nm-applet)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(nm-connection-editor)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(hyprpolkitagent)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(org.freedesktop.impl.portal.desktop.gtk)$" } })
hl.window_rule({ opacity = "0.80 $& 0.70 $& 1", match = { class = "^(org.freedesktop.impl.portal.desktop.hyprland)$" } })
hl.window_rule({ opacity = "0.70 $& 0.70 $& 1", match = { class = "^([Ss]team)$" } })
hl.window_rule({ opacity = "0.70 $& 0.70 $& 1", match = { class = "^(steamwebhelper)$" } })
hl.window_rule({ opacity = "0.70 $& 0.70 $& 1", match = { class = "^([Ss]potify)$" } })
hl.window_rule({ opacity = "0.70 $& 0.70 $& 1", match = { initial_title = "^(Spotify Free)$" } })
hl.window_rule({ opacity = "0.70 $& 0.70 $& 1", match = { initial_title = "^(Spotify Premium)$" } })
hl.window_rule({ opacity = "1.00 $& 1.00 $& 1", match = { class = "^(blender)$" } })

hl.window_rule({ opacity = "0.90 0.90", match = { class = "^(com.github.rafostar.Clapper)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(com.github.tchx84.Flatseal)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(hu.kramo.Cartridges)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(com.obsproject.Studio)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(gnome-boxes)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(vesktop)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(discord)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(WebCord)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(ArmCord)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(app.drey.Warp)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(net.davidotek.pupgui2)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(yad)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(Signal)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(io.github.alainm23.planify)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(io.gitlab.theevilskeleton.Upscaler)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(com.github.unrud.VideoDownloader)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(io.gitlab.adhami3310.Impression)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(io.missioncenter.MissionCenter)$" } })
hl.window_rule({ opacity = "0.80 0.80", match = { class = "^(io.github.flattool.Warehouse)$" } })

-- Float Rules
hl.window_rule({ float = true, match = { class = "^(Signal)$" } })
hl.window_rule({ float = true, match = { class = "^(com.github.rafostar.Clapper)$" } })
hl.window_rule({ float = true, match = { class = "^(app.drey.Warp)$" } })
hl.window_rule({ float = true, match = { class = "^(net.davidotek.pupgui2)$" } })
hl.window_rule({ float = true, match = { class = "^(yad)$" } })
hl.window_rule({ float = true, match = { class = "^(eog)$" } })
hl.window_rule({ float = true, match = { class = "^(io.github.alainm23.planify)$" } })
hl.window_rule({ float = true, match = { class = "^(io.gitlab.theevilskeleton.Upscaler)$" } })
hl.window_rule({ float = true, match = { class = "^(com.github.unrud.VideoDownloader)$" } })
hl.window_rule({ float = true, match = { class = "^(io.gitlab.adhami3310.Impression)$" } })
hl.window_rule({ float = true, match = { class = "^(io.missioncenter.MissionCenter)$" } })
hl.window_rule({ float = true, match = { title = "^(Friends List)$" } })
hl.window_rule({ float = true, match = { title = "^(Steam Settings)$" } })
hl.window_rule({ float = true, match = { initial_title = "^(Image Editor)$", class = "^(blender)$" } })
hl.window_rule({
	size = "(monitor_w*0.5) (monitor_h*0.5)",
	match = { initial_title = "^(Image Editor)$", class = "^(blender)$" },
})
hl.window_rule({ float = true, match = { initial_title = "^(Ghidra: NO ACTIVE PROJECT)" } })

-- IDE Workarounds
hl.window_rule({ no_initial_focus = true, match = { class = "^(.*jetbrains.*)$", title = "^(win[0-9]+)$" } })

-- Layer Rules
hl.config({
	layerrule = {
		"blur true,match:namespace rofi",
		"ignore_alpha 0,match:namespace rofi",
		"blur true,match:namespace notifications",
		"ignore_alpha 0,match:namespace notifications",
		"blur true,match:namespace swaync-notification-window",
		"ignore_alpha 0,match:namespace swaync-notification-window",
		"blur true,match:namespace swaync-control-center",
		"ignore_alpha 0,match:namespace swaync-control-center",
		"blur true,match:namespace logout_dialog",
	},
})

----------------------------------
---- BIND PARSER & APPLIER    ----
----------------------------------

local final_binds_config = {}

-- Loop through categories -> subgroups -> binds
for _, category in ipairs(keybindings.categories) do
	if category.subgroups then
		for _, subgroup in ipairs(category.subgroups) do
			if subgroup.binds then
				for _, b in ipairs(subgroup.binds) do
					local modStr = b.mod or ""
					local actionStr = b.action or ""

					-- 1. Replace $variables with their values from keybindings.variables
					for varName, varValue in pairs(keybindings.variables) do
						-- Escape the '$' for Lua's pattern matching
						modStr = string.gsub(modStr, "%$" .. varName, varValue)
						actionStr = string.gsub(actionStr, "%$" .. varName, varValue)
					end

					-- 2. Format the string for Hyprland
					local bindString
					if string.match(b.type, "d") and b.desc then
						-- Types with descriptions (bindd, binddm, etc) format: MOD, KEY, DESCRIPTION, ACTION
						bindString = string.format("%s, %s, %s, %s", modStr, b.key, b.desc, actionStr)
					else
						-- Standard format: MOD, KEY, ACTION
						bindString = string.format("%s, %s, %s", modStr, b.key, actionStr)
					end

					-- 3. Group them by their specific bind type (bind, bindd, bindm, bindde, etc.)
					if not final_binds_config[b.type] then
						final_binds_config[b.type] = {}
					end

					table.insert(final_binds_config[b.type], bindString)
				end
			end
		end
	end
end

-- 4. Pass the entire formatted table to Hyprland to actually apply them
hl.config(final_binds_config)
